on:
  push:

jobs:
  basic-build:
    runs-on: docker
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v6
      - uses: https://forgejo.app.jumpdrive.dev/actions/setup-rust-toolchain@v1
      - run: cargo build --release